name: E2E Test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/e2e.yml'
      - 'pnpm-lock.yaml'
      - 'src/**/*.ts'
      - 'src/**/*.vue'
      - 'tests/e2e/**/*.spec.ts'
  pull_request:
    paths:
      - '.github/workflows/e2e.yml'
      - 'pnpm-lock.yaml'
      - 'src/**/*.ts'
      - 'src/**/*.vue'
      - 'tests/e2e/**/*.spec.ts'
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      DEBUG: 0
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /home/runner/.local/share/pnpm/store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: pnpm test:ci-e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30
