on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v5.0.0
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22

      - run: |
          pnpm i --frozen-lockfile
          pnpm build

      - uses: JS-DevTools/npm-publish@v3.1.1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Create Tag
        if: ${{ steps.publish.outputs.type }}
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v2.2.2
        if: steps.create_tag.outputs.successful
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (Uninen|renovate-bot|Renovate Bot|renovate\\[bot\\]|Mend Renovate)
          show-emoji: false

      - name: Get the changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"

      - name: Create Release
        uses: ncipollo/release-action@v1.15.0
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.changelog }}

            Compare changes: ${{ steps.changelog.outputs.compareurl }}

            Read more from the Changelog: https://github.com/slipmatio/ui/blob/main/CHANGES.md
