name: Build + Test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'pnpm-lock.yaml'
      - 'src/**/*.ts'
      - 'src/**/*.vue'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'pnpm-lock.yaml'
      - 'src/**/*.ts'
      - 'src/**/*.vue'
  workflow_dispatch:

concurrency:
  group: front-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEBUG: 0

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install front
        run: pnpm i --frozen-lockfile

      # - name: Install playwright browsers
      #   run: pnpm i
      #   working-directory: front

      - name: Build front
        run: pnpm build

      - name: Test front
        run: pnpm coverage

      - name: Component Coverage
        uses: davelosert/vitest-coverage-report-action@v1.4.0
        if: ${{ always() }}
        with:
          working-directory: ./
          vite-config-path: ./vite.config.ts
