name: Tests

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/tests.yml"
      - "pnpm-lock.yaml"
      - "src/**/*.ts"
      - "src/**/*.vue"
      - "tests/**/*.ts"
  pull_request:
    paths:
      - ".github/workflows/tests.yml"
      - "pnpm-lock.yaml"
      - "src/**/*.ts"
      - "src/**/*.vue"
      - "tests/**/*.ts"
  workflow_dispatch:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      CI: 1
      DEBUG: 0
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/cache@v4.3.0
        with:
          path: /home/runner/.local/share/pnpm/store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4.2.0
        with:
          version: 10
          run_install: true
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Type Check
        run: pnpm ts

      - name: Build front
        run: pnpm build

      - name: Test front
        run: pnpm coverage

      - name: Component Coverage
        uses: davelosert/vitest-coverage-report-action@v2.8.3
        if: ${{ always() }}
        with:
          working-directory: ./
          vite-config-path: ./vite.config.ts

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: pnpm test:ci-e2e

      - uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30
